<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/DataAnalysisExampleA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

##**Basic Numpy Arrays**

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1] #mostra os valores da posição 1 até a anterior a ultima

array([2, 3])

In [9]:
a[::2] #pula de dois em dois

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])

---

##**Array Types**

In [ ]:
a

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype    #contém valores float

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=float)  #mesmo sendo inteiros posso criar usando o tipo float

array([1., 2., 3., 4.])

In [22]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
c = np.array(['a', 'b', 'c'])

In [24]:
c.dtype

dtype('<U1')

---

##**Dimensions and shapes**

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
A.shape

(2, 3)

In [27]:
A.ndim #quantas dimensões

2

In [28]:
A.size #tamanho(número total de elementos)

6

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim

3

In [33]:
B.size

12

---

##**Indexing and Slicing of Matrices**

In [34]:
A = np.array ([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [35]:
A[1] #linha na posição 1

array([4, 5, 6])

In [36]:
A[1][0] #linha na posição 1 e coluna na posição 0

np.int64(4)

In [38]:
A[1, 0]  #multi dimensional selection of numpy

np.int64(4)

In [39]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
A[:, :2] #todas as linhas, mas somente até a coluna 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [42]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
#modificação

In [43]:
A[1] = np.array([10, 10, 10])

In [44]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [45]:
A[2] = 99

In [46]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

---

##**Summary Statistics**

In [47]:
a = np.array([1, 2, 3, 4])

In [48]:
a.sum()

np.int64(10)

In [49]:
a.mean()

np.float64(2.5)

In [50]:
a.std() #desvio padrão

np.float64(1.118033988749895)

In [52]:
a.var() #variância

np.float64(1.25)

In [53]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [54]:
A.sum()

np.int64(45)

In [55]:
A.mean()

np.float64(5.0)

In [56]:
A.std()

np.float64(2.581988897471611)

In [57]:
A.var()

np.float64(6.666666666666667)

In [58]:
A.sum(axis=0) #soma das colunas

array([12, 15, 18])

In [59]:
A.sum(axis=1) #soma das linhas

array([ 6, 15, 24])

In [61]:
A.mean(axis=0)

array([4., 5., 6.])

In [62]:
A.mean(axis=1)

array([2., 5., 8.])