<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/NumpyBooleanArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

##**Boolean arrays**
_(Also called masks)_

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a[[0, -1]] #lista de índices

array([0, 3])

In [5]:
a[[True, False, True, False]]

array([0, 2])

In [6]:
a >= 2

array([False, False,  True,  True])

In [7]:
a[a >=2]

array([2, 3])

In [8]:
a.mean()

np.float64(1.5)

In [9]:
a[a > a.mean()]

array([2, 3])

In [12]:
a[~(a > a.mean())] #valores de a que não são maiores que a média

array([0, 1])

In [13]:
a[(a==0 | (a==1))]

array([0, 1])

In [14]:
a[(a <= 2) & (a % 2 ==0)]

array([0, 2])

In [15]:
#np.random acessa a parte do NumPy responsável por gerar valores aleatórios.
#randint(100) gera número aleatório entre 0 e 99
A = np.random.randint(100, size =(3, 3))

In [16]:
A

array([[49, 20, 43],
       [81, 77, 99],
       [52, 93, 87]])

In [17]:
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
A[A > 30]

array([49, 43, 81, 77, 99, 52, 93, 87])