<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/NumpyAlgebraandSize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

##**Linear Algebra**

In [3]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8 , 9]
])

In [4]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [7]:
#multiplicação matricial

In [5]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [6]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [9]:
B.T #transposta

array([[6, 4, 2],
       [5, 3, 1]])

In [10]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

---

##**Size of objects in Memory**

###**ints, floats**

In [11]:
# An integer in python is > 24bytes
sys.getsizeof(1)

28

In [12]:
# longs are even larger
sys.getsizeof(10**100)

72

In [14]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [15]:
np.dtype(float).itemsize

8

###**Lists are even larger**

In [17]:
# A one-element list
sys.getsizeof([1])

64

In [18]:
# An array of one element in numpy
np.array([1]).nbytes

8

###**And performance is also important**

In [20]:
l = list(range(100))

In [19]:
a = np.arange(100)

In [25]:
%time np.sum(a ** 2)

CPU times: user 54 µs, sys: 0 ns, total: 54 µs
Wall time: 55.3 µs


np.int64(328350)

In [24]:
%time sum([x ** 2 for x in l])

CPU times: user 14 µs, sys: 1 µs, total: 15 µs
Wall time: 15.7 µs


328350

---

##**Useful Numpy functions**

`random`

In [29]:
np.random.random(size=2) # acessa o módulo random do NumPy e usa a função random() para gerar 2 números aleatórios entre 0 e 1

array([0.23671761, 0.48116259])

In [30]:
np.random.normal(size=2) # gera 2 números aleatórios seguindo uma distribuição normal, com média 0 e desvio padrão 1

array([0.69196902, 0.50144761])

In [31]:
np.random.rand(2, 4) # gera uma matriz com 2 linhas e 4 colunas, preenchida com números decimais aleatórios entre 0 e 1.

array([[0.23389711, 0.05160725, 0.50497923, 0.4252335 ],
       [0.92989658, 0.61119536, 0.9615768 , 0.31155011]])

`arange`



In [32]:
np.arange(10) # cria um array com os números de 0 a 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

`reshape`

In [35]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

`linspace`

In [37]:
np.linspace(0, 1, 5)  #np.linspace(início, fim, quantidade)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [39]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

`zeros, ones, empty`

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [50]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

`identity` and `eye`

In [54]:
np.identity(3) # matriz identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.eye(3,3) # cria identidade e permite matriz retangular ou diagonal deslocada


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
"Hello, world"[6]

' '