<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

##**Boadcasting and Vectorized operations**

In [4]:
a = np.arange(4) #cria um array Numpy com números inteiros começando em 0 e indo até antes de 4.

In [10]:
a

array([0, 1, 2, 3])

In [11]:
a + 10  #operação aplicada a cada elemento do array

array([10, 11, 12, 13])

In [13]:
a * 10

array([ 0, 10, 20, 30])

In [14]:
a  #elementos nao alteraram pois foi criado um novo array

array([0, 1, 2, 3])

In [15]:
a += 100

In [16]:
a

array([100, 101, 102, 103])

In [17]:
l = [0, 1, 2, 3] #lista

In [18]:
[i * 10 for i in l] #operação aplicada a cada elemento da lista

[0, 10, 20, 30]

In [19]:
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
b = np.array([10, 10, 10, 10])

In [22]:
a + b

array([10, 11, 12, 13])

In [23]:
a * b

array([ 0, 10, 20, 30])

---